// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ogUAiZzsROd_2eDg4c4JM1BoSTHpWgs',
    appId: '1:547254181492:web:73ee4bc8a470be8cc03b21',
    messagingSenderId: '547254181492',
    projectId: 'ttgk4conca',
    authDomain: 'ttgk4conca.firebaseapp.com',
    databaseURL: 'https://ttgk4conca-default-rtdb.firebaseio.com',
    storageBucket: 'ttgk4conca.firebasestorage.app',
    measurementId: 'G-C14Z81WD76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh4iCH5C_vnwfKfoHLjgs1amGkXnKdbr4',
    appId: '1:547254181492:android:da836ef8b4e9d385c03b21',
    messagingSenderId: '547254181492',
    projectId: 'ttgk4conca',
    databaseURL: 'https://ttgk4conca-default-rtdb.firebaseio.com',
    storageBucket: 'ttgk4conca.firebasestorage.app',
  );

}